import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Car from '../components/animations/Car'
import Filters from '../components/Filters'
import SearchButton from '../components/common/SearchButton'
import SearchInput from '../components/common/SearchInput'
import Navbar from '../components/Navbar'
const Home: NextPage = () => {
  const router = useRouter()

  const navigate = () => {
    router.push('/search')
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700;900&display=swap" rel="stylesheet" />
      </Head>
      <div className='flex flex-col'>
        <main id="home" className='h-screen w-screen flex relative'>
            <Navbar />
            <div className='w-full flex flex-col'>
              <div className='z-10 bg-transparent h-full'>
                <h1 className='text-white font-black text-7xl overflow-hidden	pt-32 text-center'>Search The Best<br /> Game For You</h1>
                  <div className='flex flex-col items-center'>
                    <div className='flex pt-8 justify-center'>
                      <SearchInput />
                      <div className='w-24 h-16 rounded-lg ml-4'>
                        <SearchButton onClick={() => navigate()}/>
                      </div>
                    </div>
                  </div>
              </div>
              <Car />
            </div>
        </main>
      </div>
    </div>
  )
}

export default Home
