import type { NextPage } from 'next'
import Head from 'next/head'
import Car from '../components/animations/Car'
import Navbar from '../components/animations/Navbar'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700;900&display=swap" rel="stylesheet" />
      </Head>
      <div className='flex flex-row'>
        <main id="home" className='h-screen w-screen flex relative'>
          {/* <Navbar /> */}
            <div className='w-full flex flex-col'>
              <div>
                <h1 className='text-white font-black text-7xl pt-36 text-center'>Search The Best<br /> Game For You</h1>
              </div>
              <Car />
            </div>
        </main>
      </div>
    </div>
  )
}

export default Home
